language: ruby

env:
  - RAILS_ENV=test

cache:
  bundler: true

services:
  - mysql

bundler_args: --without test --jobs 3 --retry 3

before_install:
  - cp config/database.yml.sample config/database.yml
  - mysql -e "CREATE DATABASE omnistore_test;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON omnistore_test.* TO 'travis'@'%';";
